### ISSUE TITLE
Make jsbin optional by including explanations

### ISSUE THREAD

**Issue by ghost** [miguelmota/javascript-idiosyncrasies#10]
This is a fun resource, but I find using it somewhat troublesome because one needs to jump between jsbin and your repo. If you are keen to suggestions, I propose refactoring the guide so that jsbin becomes optional.

**Comment by miguelmota** [comment]
Yeah thought about that, I didn't want to make the readme super long. Maybe I or someone should make a quiz style microsite with runnable examples.
