### ISSUE TITLE
should be 1?

### ISSUE THREAD

**Issue by craigmingtaozhang** [miguelmota/javascript-idiosyncrasies#7]
(function() {
        var x = 1;
        return (function () {
            return x;
            var x = 2;
        })();
    })();

**Comment by miguelmota** [comment]
Because of the [hoisting](http://www.adequatelygood.com/JavaScript-Scoping-and-Hoisting.html) that goes behind the scenes, x is undefined when it gets returned.

[http://jsbin.com/puboreqiqo/1/edit?js,console](http://jsbin.com/puboreqiqo/1/edit?js,console)

**Comment by craigmingtaozhang** [comment]
I see. Thank you!
